### ISSUE TITLE
Couldn't handle login status on github.com

### ISSUE THREAD

**Issue by tricknotes** [tricknotes/nothub#10]
When I logged in to github.com, nothub says that please login :<
<img width="470" alt="2017-08-22 16 56 33" src="https://user-images.githubusercontent.com/290782/29554641-df3f34e6-875a-11e7-8e7b-2b6d0dc7efc9.png">

This issue was reported by @fukajun .

**Comment by tricknotes** [comment]
Now I released a new version [0.4.12](https://github.com/tricknotes/nothub/tree/v0.4.12) including fix for this issue.

@fukajun
If it is not fixed yet, please mention me :-)

**Comment by fukajun** [comment]
thank your for faster updating. 👍 
Extension is fixed!
