### ISSUE TITLE
Ability to ignore starring

### ISSUE THREAD

**Issue by vendethiel** [tricknotes/nothub#6]
Hi and thanks for this nice addon.

Currently, on repo options, we have ["others"](https://github.com/tricknotes/nothub/blob/master/src/js/query_builder.coffee#L115).
This includes starring, which is nice, cause I don't want to get spammed on big repos I follow.
Sadly this also includes `PullRequestReviewCommentEvent`. Would you mind moving that in  the "pullreq" repo type ?

**Comment by vendethiel** [comment]
hi @tricknotes , are you interested in such a feature?

**Comment by tricknotes** [comment]
Yes, I'm agree with this feature.

To introduce this, some data migration code is required. (The user data is stored to localStrage.)
But now I have not enough time to implement it.
If you are interested in it, I always welcome your PR.
